language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
  - brew update
  - brew install xctool --HEAD  
script:
  - ./script/run-test.sh
after_success:
  - ./script/coveralls.sh -r ./ -e Pods -e Tests